before:
  hooks:
    - go mod tidy
    - go build -o build/output/kvm-agent -ldflags '-s -w' ./main.go
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux

nfpms:
  - 
    id: "kvm-agent"
    package_name: "kvm-agent"
    formats:
      - rpm
    maintainer: "Asklv"
    description: Collect system data and report to data source.
    vendor: "kvm-agent"
    license: "MIT"
    # changelog: "changelog.yaml"
    contents:
      # - src: ./build/output/kvm-agent
      #   dst: /usr/bin/kvm-agent
      - src: ./build/output/config.yaml
        dst: /etc/kvm-agent/config.yaml
        type: config
      - src: /usr/bin/kvm-agent
        dst: /sbin/kvm-agent
        type: symlink
      - src: ./build/systemd/kvm-agent.service
        dst: /lib/systemd/system/kvm-agent.service
    overrides:
      rpm:
        scripts:
          preinstall: ./build/scripts/preinstall.sh
          postremove: ./build/scripts/postremove.sh