############################################################
############################################################
#   _  ___     ____  __         _                    _     #
#  | |/ | \   / /  \/  |       / \   __ _  ___ _ __ | |_   #
#  | ' / \ \ / /| |\/| |_____ / _ \ / _` |/ _ \ '_ \| __|  #
#  | . \  \ V / | |  | |_____/ ___ \ (_| |  __/ | | | |_   #
#  |_|\_\  \_/  |_|  |_|    /_/   \_\__, |\___|_| |_|\__|  #
#                                   |___/                  #
############################################################
############################################################

app:
  version: 1.0.0
  debug: true # debug mode
  log_file: ./logs # log mode

agent:
  uuid: 6e8c2828-5460-49a2-99a9-6ed809ae4d1d # agent uuid
  period: 3 # collect data every 3 seconds
  gzip: true # compress report data

redis:
  ip: 127.0.0.1
  port: 6379
  password: utyCyszHbhR9w5XX
  db: 0

dm:
  ip: 127.0.0.1
  port: 5236
  username: SYSDBA
  password: SYSDBA