############################################################
############################################################
#   _  ___     ____  __         _                    _     #
#  | |/ | \   / /  \/  |       / \   __ _  ___ _ __ | |_   #
#  | ' / \ \ / /| |\/| |_____ / _ \ / _` |/ _ \ '_ \| __|  #
#  | . \  \ V / | |  | |_____/ ___ \ (_| |  __/ | | | |_   #
#  |_|\_\  \_/  |_|  |_|    /_/   \_\__, |\___|_| |_|\__|  #
#                                   |___/                  #
############################################################
############################################################

app:
  version: 1.0.0
  debug: true # debug mode
  log_file: /var/log/kvm-agent # log mode
  ban_monitor: true # monitor mode

server:
  ip: 0.0.0.0
  port: 6000

agent:
  uuid: 6e8c2828-5460-49a2-99a9-6ed809ae4d1d # agent uuid
  period: 10 # collect data every 5 seconds
  gzip: true # compress report data

redis:
  ip: 127.0.0.1
  port: 6379
  password: utyCyszHbhR9w5XX
  db: 0

dm:
  ip: 127.0.0.1
  port: 5236
  username: SYSDBA
  password: SYSDBA

hardware:
  ipmi_enable: false
  snmp_enable: true

ipmi:
  - name: bmc1
    ip: 168.66.1.106
    port: 623
    username: root
    password: 0penBmc
  - name: bmc2
    ip: 168.66.1.107
    port: 623
    username: root
    password: 0penBmc
  - name: bmc3
    ip: 168.66.1.108
    port: 623
    username: root
    password: 0penBmc
  - name: bmc4
    ip: 168.66.1.109
    port: 623
    username: root
    password: 0penBmc

snmp: # 2c version
  - name: snmp1
    ip: 127.0.0.1
    port: 161
    community: public