name: Build and Release RPM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.20"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build
        run: make clean && make build

      - name: Package and Publish Release
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          build: nfpm
          args: release --rm-dist

      - name: Build RPM
        run: make build-rpm

      - name: Publish RPM Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/tmp/kvm-agent_${{ github.ref }}_arm64.rpm
          asset_name: kvm-agent${{ github.ref }}_arm64.rpm
          asset_content_type: application/octet-stream